export interface WordEntry {
  word: string;
  hint: string;
}

export const WORD_LIST: WordEntry[] = [
  { word: 'Spider-Man', hint: 'Superheroes' },
  { word: 'Batman', hint: 'Superheroes' },
  { word: 'Wonder Woman', hint: 'Superheroes' },
  { word: 'Iron Man', hint: 'Marvel Superheroes' },
  { word: 'Black Panther', hint: 'Marvel Superheroes' },
  { word: 'The Flash', hint: 'Superheroes' },
  { word: 'Barbie', hint: 'Blockbuster Movies' },
  { word: 'Oppenheimer', hint: 'Blockbuster Movies' },
  { word: 'The Avengers', hint: 'Marvel Movies' },
  { word: 'Avatar', hint: 'Blockbuster Movies' },
  { word: 'Shrek', hint: 'Animated Movies' },
  { word: 'Titanic', hint: 'Classic Blockbusters' },
  { word: 'Inception', hint: 'Mind-Bending Thrillers' },
  { word: 'Stranger Things', hint: 'Netflix Original Shows' },
  { word: 'Squid Game', hint: 'Korean Drama Series' },
  { word: 'Breaking Bad', hint: 'Crime TV Dramas' },
  { word: 'Game of Thrones', hint: 'Fantasy TV Series' },
  { word: 'The Office', hint: 'Workplace Sitcoms' },
  { word: 'The Mandalorian', hint: 'Star Wars Streaming Shows' },
  { word: 'Wednesday', hint: 'Netflix Shows' },
  { word: 'Taylor Swift', hint: 'Pop Music Artists' },
  { word: 'Beyoncé', hint: 'Music Icons' },
  { word: 'Bad Bunny', hint: 'Latin Music Artists' },
  { word: 'Olivia Rodrigo', hint: 'Pop Music Artists' },
  { word: 'Drake', hint: 'Hip-Hop Artists' },
  { word: 'BTS', hint: 'K-Pop Groups' },
  { word: 'Billie Eilish', hint: 'Pop Music Artists' },
  { word: 'Dua Lipa', hint: 'Pop Music Artists' },
  { word: 'Harry Styles', hint: 'Pop Music Artists' },
  { word: 'BLACKPINK', hint: 'K-Pop Groups' },
  { word: 'The Weeknd', hint: 'R&B Artists' },
  { word: 'Sabrina Carpenter', hint: 'Pop Music Artists' },
  { word: 'Minecraft', hint: 'Sandbox Video Games' },
  { word: 'Fortnite', hint: 'Battle Royale Games' },
  { word: 'Among Us', hint: 'Online Party Games' },
  { word: 'Roblox', hint: 'Online Gaming Platforms' },
  { word: 'GTA', hint: 'Open World Video Games' },
  { word: 'The Legend of Zelda', hint: 'Classic Video Game Franchises' },
  { word: 'Call of Duty', hint: 'First-Person Shooter Games' },
  { word: 'Elden Ring', hint: 'Action RPG Games' },
  { word: 'TikTok', hint: 'Social Media Apps' },
  { word: 'Instagram', hint: 'Social Media Apps' },
  { word: 'ChatGPT', hint: 'AI Technology' },
  { word: 'Netflix', hint: 'Streaming Platforms' },
  { word: 'Spotify', hint: 'Music Streaming Apps' },
  { word: 'iPhone', hint: 'Smartphones' },
  { word: 'Wordle', hint: 'Online Word Games' },
  { word: 'Harry Potter', hint: 'Fantasy Book & Movie Franchises' },
  { word: 'Star Wars', hint: 'Sci-Fi Movie Franchises' },
  { word: 'Elon Musk', hint: 'Tech Billionaires' },
  { word: 'The Rock', hint: 'Celebrity Actors & Athletes' },
  { word: 'Kim Kardashian', hint: 'Reality TV Celebrities' },
  { word: 'Boba Tea', hint: 'Trendy Drinks' },
  { word: 'Birria Tacos', hint: 'Viral Food Trends' },
  { word: 'Avocado Toast', hint: 'Millennial Food Trends' },
];
